apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cni-gcp
spec:
  components:
    cni:
      namespace: kube-system
      enabled: true
  values:
    cni:
      cniBinDir: /home/kubernetes/bin
      excludeNamespaces:
        - istio-system
        - kube-system
        # [END docs]
# [END docs]
