apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: iap-operator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - name: status-port
                protocol: TCP
                port: 15021
                targetPort: 15021
                nodePort: 31223 # kpt-set: ${gcloud.container.cluster.ingress.statusPort}
              - name: http2
                port: 80
                targetPort: 8080
                nodePort: 31224 # kpt-set: ${gcloud.container.cluster.ingress.httpPort}
              - name: https
                port: 443
                targetPort: 8443
              - name: tcp-istiod
                port: 15012
                targetPort: 15012
              - name: tls
                port: 15443
                targetPort: 15443
