apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: revisioned-istio-ingressgateway
spec:
  components:
    ingressGateways:
      # Disable istio-ingressgateway to avoid downtime from in-place upgrade
      - name: istio-ingressgateway
        enabled: false
      # Workaround to use revision based deployments for istio-ingressgateway
      - name: istio-ingressgateway-ASM_REV # kpt-set: istio-ingressgateway-${anthos.servicemesh.rev}
        enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2
          # Rename the service to still use istio-ingressgateway
          overlays:
            - name: istio-ingressgateway-ASM_REV # kpt-set: istio-ingressgateway-${anthos.servicemesh.rev}
              apiVersion: extensions/v1beta1
              kind: Service
              patches:
                - value: istio-ingressgateway
                  path: metadata.name
