apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: INGRESSGATEWAY_NAME # kpt-set: ${anthos.servicemesh.custom-ingressgateway-name}
spec:
  components:
    ingressGateways:
      - name: INGRESSGATEWAY_NAME-ASM_REV # kpt-set: ${anthos.servicemesh.custom-ingressgateway-name}-${anthos.servicemesh.rev}
        namespace: istio-system # kpt-set: ${anthos.servicemesh.custom-ingressgateway-namespace}
        enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2
          # Rename the service to still use istio-ingressgateway
          overlays:
            - name: INGRESSGATEWAY_NAME-ASM_REV # kpt-set: ${anthos.servicemesh.custom-ingressgateway-name}-${anthos.servicemesh.rev}
              apiVersion: extensions/v1beta1
              kind: Service
              patches:
                - value: INGRESSGATEWAY_NAME # kpt-set: ${anthos.servicemesh.custom-ingressgateway-name}
                  path: metadata.name
