apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: vm
spec:
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        enabled: true
        k8s:
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
          env:
            # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
        label:
          app: istio-eastwestgateway
          istio: eastwestgateway
